# Download flat files
This was only possible from April 2024. We simply download everything and extract them to single ticker files.

In [1]:
import os
import pytz
import gzip
import calendar
import pandas as pd
from datetime import datetime, date, time, timedelta
from pytz import timezone
from times import get_market_dates
from fastparquet import write
import boto3
from botocore.config import Config
from dotenv import load_dotenv 

# Now load variables and define constants
load_dotenv() # to load variables from .env

ACCESS_KEY_ID = os.environ.get("ACCESS_KEY_ID")
if not ACCESS_KEY_ID:
    raise ValueError("No API key found. Please set ACCESS_KEY_ID in your .env file.")

API_KEY = os.environ.get("MASSIVE_API_KEY")
if not API_KEY:
    raise ValueError("No API key found. Please set MASSIVE_API_KEY in your .env file.")

session = boto3.Session(
   aws_access_key_id=ACCESS_KEY_ID,
   aws_secret_access_key=API_KEY,
)
s3 = session.client(
   's3',
   endpoint_url='https://files.polygon.io',
   config=Config(signature_version='s3v4'),
)

DATA_PATH = "../data/polygon/"

START_DATE = date(2016, 6, 1) # only go as far as your polygon membership allows. don't waste loop cycles
END_DATE = date(2016, 6, 11) # till today only or else you will get "out of range" from our custom function and don't waste loop cycles

# START_DATE = date(2016, 6, 1) # only go as far as your polygon membership allows. don't waste loop cycles

# till today only or else you will get "out of range" from our custom function and don't waste loop cycles
# this will need updating everyday so that we only fetch the new adjustments in an idempotent way
# END_DATE = date(2026, 6, 15)

# Initial download
Download everything

In [2]:
# for day in get_market_dates(START_DATE, END_DATE):
#     destination = DATA_PATH + f'raw/flatfiles/{day.isoformat()}.csv.gz'
#     s3.download_file('flatfiles', 
#                 f'us_stocks_sip/minute_aggs_v1/{day.year}/{day.strftime("%m")}/{day.isoformat()}.csv.gz', 
#                 destination)

In [3]:
df = pd.read_csv(DATA_PATH + f"raw/flatfiles/2016-06-06.csv.gz")
df

,ticker,volume,open,close,high,low,window_start,transactions
0,A,16484,45.72,45.780,45.78,45.72,1465219920000000000,35
1,A,1128,45.82,45.840,45.84,45.81,1465219980000000000,22
2,A,2637,45.81,45.845,45.88,45.81,1465220040000000000,31
3,A,953,45.84,45.800,45.84,45.80,1465220100000000000,18
4,A,4591,45.80,45.760,45.81,45.75,1465220160000000000,46
...,...,...,...,...,...,...,...,...
1263825,ZYNE,466,9.67,9.680,9.68,9.67,1465242840000000000,8
1263826,ZYNE,693,9.67,9.685,9.69,9.67,1465242960000000000,10
1263827,ZYNE,500,9.68,9.690,9.69,9.68,1465243020000000000,7
1263828,ZYNE,296,9.69,9.690,9.69,9.69,1465243080000000000,10
1263829,ZYNE,1445,9.70,9.700,9.70,9.67,1465243140000000000,27

Extract and concatenate into monthly files

In [4]:
def concatenate_and_save(start_date, end_date, file_name):
    # Get a list of what we already have
    files = []
    # available_files = os.listdir(DATA_PATH + 'raw/flatfiles')
    # available_dates = [date.fromisoformat(file.replace(".csv.gz", "")) for file in available_files if file.endswith(".csv.gz")]
    
    market_dates = get_market_dates(start_date, end_date)
    if len(market_dates) == 0:
        return
    for day in market_dates:
        # if day >= start_date and day <= end_date and day in available_dates:
        destination = DATA_PATH + f'raw/flatfiles/{day.isoformat()}.csv.gz'
        with gzip.open(destination) as f:
            all_bars = pd.read_csv(f)
            all_bars = all_bars[['window_start', 'ticker', 'open', 'high', 'low', 'close', 'volume', 'transactions']]
            all_bars = all_bars.rename(columns={'window_start': 'datetime'})
            all_bars = all_bars.set_index('datetime')
            all_bars.index = pd.to_datetime(all_bars.index, unit='ns') # Convert to datetime (UTC-naive)
            # Make UTC aware (in order to convert)
            # Convert UTC to ET
            # Make timezone naive
            all_bars.index = all_bars.index.tz_localize(pytz.UTC).tz_convert("US/Eastern").tz_localize(None)  

            files.append(all_bars)
            print(day)
        
    all_bars = pd.concat(files)
    all_bars = all_bars.reset_index()
    all_bars = all_bars.set_index('ticker')
    all_bars = all_bars.sort_index()

    all_bars.to_parquet(DATA_PATH + f"raw/flatfiles/monthly_parquet/{file_name}.parquet", engine="fastparquet", compression="snappy", row_group_offsets=25000)

In [5]:
# for year in range(2016, 2016 + 1):
for year in range(2016, 2026 + 1):
    files = []
    # for month in range(6, 6 + 1):
    for month in range(1, 12 + 1):
        _, end_date = calendar.monthrange(year, month)
        concatenate_and_save(date(year, month, 1), date(year, month, end_date), f"{year}-{month}")

2016-06-06
2016-06-07
2016-06-08
2016-06-09
2016-06-10
2016-06-13
2016-06-14
2016-06-15
2016-06-16
2016-06-17
2016-06-20
2016-06-21
2016-06-22
2016-06-23
2016-06-24
2016-06-27
2016-06-28
2016-06-29
2016-06-30
2016-07-01
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-08-01
2016-08-02
2016-08-03
2016-08-04
2016-08-05
2016-08-08
2016-08-09
2016-08-10
2016-08-11
2016-08-12
2016-08-15
2016-08-16
2016-08-17
2016-08-18
2016-08-19
2016-08-22
2016-08-23
2016-08-24
2016-08-25
2016-08-26
2016-08-29
2016-08-30
2016-08-31
2016-09-01
2016-09-02
2016-09-06
2016-09-07
2016-09-08
2016-09-09
2016-09-12
2016-09-13
2016-09-14
2016-09-15
2016-09-16
2016-09-19
2016-09-20
2016-09-21
2016-09-22
2016-09-23
2016-09-26
2016-09-27
2016-09-28
2016-09-29
2016-09-30
2016-10-03
2016-10-04
2016-10-05
2016-10-06
2016-10-07
2016-10-10
2016-10-11
2016-10-12
2016-10-13
2016-10-14
2016-10-17
2016-10-18
2016-10-19
2016-10-20
2016-10-21
2016-10-24
2016-10-25
2016-10-26
2016-10-27
2016-10-28
2016-10-31
2016-11-01
2016-11-02
2016-11-03
2016-11-04
2016-11-07
2016-11-08
2016-11-09
2016-11-10
2016-11-11
2016-11-14
2016-11-15
2016-11-16
2016-11-17
2016-11-18
2016-11-21
2016-11-22
2016-11-23
2016-11-25
2016-11-28
2016-11-29
2016-11-30
2016-12-01
2016-12-02
2016-12-05
2016-12-06
2016-12-07
2016-12-08
2016-12-09
2016-12-12
2016-12-13
2016-12-14
2016-12-15
2016-12-16
2016-12-19
2016-12-20
2016-12-21
2016-12-22
2016-12-23
2016-12-27
2016-12-28
2016-12-29
2016-12-30
2017-01-03
2017-01-04
2017-01-05
2017-01-06
2017-01-09
2017-01-10
2017-01-11
2017-01-12
2017-01-13
2017-01-17
2017-01-18
2017-01-19
2017-01-20
2017-01-23
2017-01-24
2017-01-25
2017-01-26
2017-01-27
2017-01-30
2017-01-31
2017-02-01
2017-02-02
2017-02-03
2017-02-06
2017-02-07
2017-02-08
2017-02-09
2017-02-10
2017-02-13
2017-02-14
2017-02-15
2017-02-16
2017-02-17
2017-02-21
2017-02-22
2017-02-23
2017-02-24
2017-02-27
2017-02-28
2017-03-01
2017-03-02
2017-03-03
2017-03-06
2017-03-07
2017-03-08
2017-03-09
2017-03-10
2017-03-13
2017-03-14
2017-03-15
2017-03-16
2017-03-17
2017-03-20
2017-03-21
2017-03-22
2017-03-23
2017-03-24
2017-03-27
2017-03-28
2017-03-29
2017-03-30
2017-03-31
2017-04-03
2017-04-04
2017-04-05
2017-04-06
2017-04-07
2017-04-10
2017-04-11
2017-04-12
2017-04-13
2017-04-17
2017-04-18
2017-04-19
2017-04-20
2017-04-21
2017-04-24
2017-04-25
2017-04-26
2017-04-27
2017-04-28
2017-05-01
2017-05-02
2017-05-03
2017-05-04
2017-05-05
2017-05-08
2017-05-09
2017-05-10
2017-05-11
2017-05-12
2017-05-15
2017-05-16
2017-05-17
2017-05-18
2017-05-19
2017-05-22
2017-05-23
2017-05-24
2017-05-25
2017-05-26
2017-05-30
2017-05-31
2017-06-01
2017-06-02
2017-06-05
2017-06-06
2017-06-07
2017-06-08
2017-06-09
2017-06-12
2017-06-13
2017-06-14
2017-06-15
2017-06-16
2017-06-19
2017-06-20
2017-06-21
2017-06-22
2017-06-23
2017-06-26
2017-06-27
2017-06-28
2017-06-29
2017-06-30
2017-07-03
2017-07-05
2017-07-06
2017-07-07
2017-07-10
2017-07-11
2017-07-12
2017-07-13
2017-07-14
2017-07-17
2017-07-18
2017-07-19
2017-07-20
2017-07-21
2017-07-24
2017-07-25
2017-07-26
2017-07-27
2017-07-28
2017-07-31
2017-08-01
2017-08-02
2017-08-03
2017-08-04
2017-08-07
2017-08-08
2017-08-09
2017-08-10
2017-08-11
2017-08-14
2017-08-15
2017-08-16
2017-08-17
2017-08-18
2017-08-21
2017-08-22
2017-08-23
2017-08-24
2017-08-25
2017-08-28
2017-08-29
2017-08-30
2017-08-31
2017-09-01
2017-09-05
2017-09-06
2017-09-07
2017-09-08
2017-09-11
2017-09-12
2017-09-13
2017-09-14
2017-09-15
2017-09-18
2017-09-19
2017-09-20
2017-09-21
2017-09-22
2017-09-25
2017-09-26
2017-09-27
2017-09-28
2017-09-29
2017-10-02
2017-10-03
2017-10-04
2017-10-05
2017-10-06
2017-10-09
2017-10-10
2017-10-11
2017-10-12
2017-10-13
2017-10-16
2017-10-17
2017-10-18
2017-10-19
2017-10-20
2017-10-23
2017-10-24
2017-10-25
2017-10-26
2017-10-27
2017-10-30
2017-10-31
2017-11-01
2017-11-02
2017-11-03
2017-11-06
2017-11-07
2017-11-08
2017-11-09
2017-11-10
2017-11-13
2017-11-14
2017-11-15
2017-11-16
2017-11-17
2017-11-20
2017-11-21
2017-11-22
2017-11-24
2017-11-27
2017-11-28
2017-11-29
2017-11-30
2017-12-01
2017-12-04
2017-12-05
2017-12-06
2017-12-07
2017-12-08
2017-12-11
2017-12-12
2017-12-13
2017-12-14
2017-12-15
2017-12-18
2017-12-19
2017-12-20
2017-12-21
2017-12-22
2017-12-26
2017-12-27
2017-12-28
2017-12-29
2018-01-02
2018-01-03
2018-01-04
2018-01-05
2018-01-08
2018-01-09
2018-01-10
2018-01-11
2018-01-12
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-12
2018-02-13
2018-02-14
2018-02-15
2018-02-16
2018-02-20
2018-02-21
2018-02-22
2018-02-23
2018-02-26
2018-02-27
2018-02-28
2018-03-01
2018-03-02
2018-03-05
2018-03-06
2018-03-07
2018-03-08
2018-03-09
2018-03-12
2018-03-13
2018-03-14
2018-03-15
2018-03-16
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-23
2018-03-26
2018-03-27
2018-03-28
2018-03-29
2018-04-02
2018-04-03
2018-04-04
2018-04-05
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-05-01
2018-05-02
2018-05-03
2018-05-04
2018-05-07
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-22
2018-05-23
2018-05-24
2018-05-25
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-06
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-13
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-21
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-02
2018-07-03
2018-07-05
2018-07-06
2018-07-09
2018-07-10
2018-07-11
2018-07-12
2018-07-13
2018-07-16
2018-07-17
2018-07-18
2018-07-19
2018-07-20
2018-07-23
2018-07-24
2018-07-25
2018-07-26
2018-07-27
2018-07-30
2018-07-31
2018-08-01
2018-08-02
2018-08-03
2018-08-06
2018-08-07
2018-08-08
2018-08-09
2018-08-10
2018-08-13
2018-08-14
2018-08-15
2018-08-16
2018-08-17
2018-08-20
2018-08-21
2018-08-22
2018-08-23
2018-08-24
2018-08-27
2018-08-28
2018-08-29
2018-08-30
2018-08-31
2018-09-04
2018-09-05
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-09-21
2018-09-24
2018-09-25
2018-09-26
2018-09-27
2018-09-28
2018-10-01
2018-10-02
2018-10-03
2018-10-04
2018-10-05
2018-10-08
2018-10-09
2018-10-10
2018-10-11
2018-10-12
2018-10-15
2018-10-16
2018-10-17
2018-10-18
2018-10-19
2018-10-22
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-29
2018-10-30
2018-10-31
2018-11-01
2018-11-02
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-09
2018-11-12
2018-11-13
2018-11-14
2018-11-15
2018-11-16
2018-11-19
2018-11-20
2018-11-21
2018-11-23
2018-11-26
2018-11-27
2018-11-28
2018-11-29
2018-11-30
2018-12-03
2018-12-04
2018-12-06
2018-12-07
2018-12-10
2018-12-11
2018-12-12
2018-12-13
2018-12-14
2018-12-17
2018-12-18
2018-12-19
2018-12-20
2018-12-21
2018-12-24
2018-12-26
2018-12-27
2018-12-28
2018-12-31
2019-01-02
2019-01-03
2019-01-04
2019-01-07
2019-01-08
2019-01-09
2019-01-10
2019-01-11
2019-01-14
2019-01-15
2019-01-16
2019-01-17
2019-01-18
2019-01-22
2019-01-23
2019-01-24
2019-01-25
2019-01-28
2019-01-29
2019-01-30
2019-01-31
2019-02-01
2019-02-04
2019-02-05
2019-02-06
2019-02-07
2019-02-08
2019-02-11
2019-02-12
2019-02-13
2019-02-14
2019-02-15
2019-02-19
2019-02-20
2019-02-21
2019-02-22
2019-02-25
2019-02-26
2019-02-27
2019-02-28
2019-03-01
2019-03-04
2019-03-05
2019-03-06
2019-03-07
2019-03-08
2019-03-11
2019-03-12
2019-03-13
2019-03-14
2019-03-15
2019-03-18
2019-03-19
2019-03-20
2019-03-21
2019-03-22
2019-03-25
2019-03-26
2019-03-27
2019-03-28
2019-03-29
2019-04-01
2019-04-02
2019-04-03
2019-04-04
2019-04-05
2019-04-08
2019-04-09
2019-04-10
2019-04-11
2019-04-12
2019-04-15
2019-04-16
2019-04-17
2019-04-18
2019-04-22
2019-04-23
2019-04-24
2019-04-25
2019-04-26
2019-04-29
2019-04-30
2019-05-01
2019-05-02
2019-05-03
2019-05-06
2019-05-07
2019-05-08
2019-05-09
2019-05-10
2019-05-13
2019-05-14
2019-05-15
2019-05-16
2019-05-17
2019-05-20
2019-05-21
2019-05-22
2019-05-23
2019-05-24
2019-05-28
2019-05-29
2019-05-30
2019-05-31
2019-06-03
2019-06-04
2019-06-05
2019-06-06
2019-06-07
2019-06-10
2019-06-11
2019-06-12
2019-06-13
2019-06-14
2019-06-17
2019-06-18
2019-06-19
2019-06-20
2019-06-21
2019-06-24
2019-06-25
2019-06-26
2019-06-27
2019-06-28
2019-07-01
2019-07-02
2019-07-03
2019-07-05
2019-07-08
2019-07-09
2019-07-10
2019-07-11
2019-07-12
2019-07-15
2019-07-16
2019-07-17
2019-07-18
2019-07-19
2019-07-22
2019-07-23
2019-07-24
2019-07-25
2019-07-26
2019-07-29
2019-07-30
2019-07-31
2019-08-01
2019-08-02
2019-08-05
2019-08-06
2019-08-07
2019-08-08
2019-08-09
2019-08-12
2019-08-13
2019-08-14
2019-08-15
2019-08-16
2019-08-19
2019-08-20
2019-08-21
2019-08-22
2019-08-23
2019-08-26
2019-08-27
2019-08-28
2019-08-29
2019-08-30
2019-09-03
2019-09-04
2019-09-05
2019-09-06
2019-09-09
2019-09-10
2019-09-11
2019-09-12
2019-09-13
2019-09-16
2019-09-17
2019-09-18
2019-09-19
2019-09-20
2019-09-23
2019-09-24
2019-09-25
2019-09-26
2019-09-27
2019-09-30
2019-10-01
2019-10-02
2019-10-03
2019-10-04
2019-10-07
2019-10-08
2019-10-09
2019-10-10
2019-10-11
2019-10-14
2019-10-15
2019-10-16
2019-10-17
2019-10-18
2019-10-21
2019-10-22
2019-10-23
2019-10-24
2019-10-25
2019-10-28
2019-10-29
2019-10-30
2019-10-31
2019-11-01
2019-11-04
2019-11-05
2019-11-06
2019-11-07
2019-11-08
2019-11-11
2019-11-12
2019-11-13
2019-11-14
2019-11-15
2019-11-18
2019-11-19
2019-11-20
2019-11-21
2019-11-22
2019-11-25
2019-11-26
2019-11-27
2019-11-29
2019-12-02
2019-12-03
2019-12-04
2019-12-05
2019-12-06
2019-12-09
2019-12-10
2019-12-11
2019-12-12
2019-12-13
2019-12-16
2019-12-17
2019-12-18
2019-12-19
2019-12-20
2019-12-23
2019-12-24
2019-12-26
2019-12-27
2019-12-30
2019-12-31
2020-01-02
2020-01-03
2020-01-06
2020-01-07
2020-01-08
2020-01-09
2020-01-10
2020-01-13
2020-01-14
2020-01-15
2020-01-16
2020-01-17
2020-01-21
2020-01-22
2020-01-23
2020-01-24
2020-01-27
2020-01-28
2020-01-29
2020-01-30
2020-01-31
2020-02-03
2020-02-04
2020-02-05
2020-02-06
2020-02-07
2020-02-10
2020-02-11
2020-02-12
2020-02-13
2020-02-14
2020-02-18
2020-02-19
2020-02-20
2020-02-21
2020-02-24
2020-02-25
2020-02-26
2020-02-27
2020-02-28
2020-03-02
2020-03-03
2020-03-04
2020-03-05
2020-03-06
2020-03-09
2020-03-10
2020-03-11
2020-03-12
2020-03-13
2020-03-16
2020-03-17
2020-03-18
2020-03-19
2020-03-20
2020-03-23
2020-03-24
2020-03-25
2020-03-26
2020-03-27
2020-03-30
2020-03-31
2020-04-01
2020-04-02
2020-04-03
2020-04-06
2020-04-07
2020-04-08
2020-04-09
2020-04-13
2020-04-14
2020-04-15
2020-04-16
2020-04-17
2020-04-20
2020-04-21
2020-04-22
2020-04-23
2020-04-24
2020-04-27
2020-04-28
2020-04-29
2020-04-30
2020-05-01
2020-05-04
2020-05-05
2020-05-06
2020-05-07
2020-05-08
2020-05-11
2020-05-12
2020-05-13
2020-05-14
2020-05-15
2020-05-18
2020-05-19
2020-05-20
2020-05-21
2020-05-22
2020-05-26
2020-05-27
2020-05-28
2020-05-29
2020-06-01
2020-06-02
2020-06-03
2020-06-04
2020-06-05
2020-06-08
2020-06-09
2020-06-10
2020-06-11
2020-06-12
2020-06-15
2020-06-16
2020-06-17
2020-06-18
2020-06-19
2020-06-22
2020-06-23
2020-06-24
2020-06-25
2020-06-26
2020-06-29
2020-06-30
2020-07-01
2020-07-02
2020-07-06
2020-07-07
2020-07-08
2020-07-09
2020-07-10
2020-07-13
2020-07-14
2020-07-15
2020-07-16
2020-07-17
2020-07-20
2020-07-21
2020-07-22
2020-07-23
2020-07-24
2020-07-27
2020-07-28
2020-07-29
2020-07-30
2020-07-31
2020-08-03
2020-08-04
2020-08-05
2020-08-06
2020-08-07
2020-08-10
2020-08-11
2020-08-12
2020-08-13
2020-08-14
2020-08-17
2020-08-18
2020-08-19
2020-08-20
2020-08-21
2020-08-24
2020-08-25
2020-08-26
2020-08-27
2020-08-28
2020-08-31
2020-09-01
2020-09-02
2020-09-03
2020-09-04
2020-09-08
2020-09-09
2020-09-10
2020-09-11
2020-09-14
2020-09-15
2020-09-16
2020-09-17
2020-09-18
2020-09-21
2020-09-22
2020-09-23
2020-09-24
2020-09-25
2020-09-28
2020-09-29
2020-09-30
2020-10-01
2020-10-02
2020-10-05
2020-10-06
2020-10-07
2020-10-08
2020-10-09
2020-10-12
2020-10-13
2020-10-14
2020-10-15
2020-10-16
2020-10-19
2020-10-20
2020-10-21
2020-10-22
2020-10-23
2020-10-26
2020-10-27
2020-10-28
2020-10-29
2020-10-30
2020-11-02
2020-11-03
2020-11-04
2020-11-05
2020-11-06
2020-11-09
2020-11-10
2020-11-11
2020-11-12
2020-11-13
2020-11-16
2020-11-17
2020-11-18
2020-11-19
2020-11-20
2020-11-23
2020-11-24
2020-11-25
2020-11-27
2020-11-30
2020-12-01
2020-12-02
2020-12-03
2020-12-04
2020-12-07
2020-12-08
2020-12-09
2020-12-10
2020-12-11
2020-12-14
2020-12-15
2020-12-16
2020-12-17
2020-12-18
2020-12-21
2020-12-22
2020-12-23
2020-12-24
2020-12-28
2020-12-29
2020-12-30
2020-12-31
2021-01-04
2021-01-05
2021-01-06
2021-01-07
2021-01-08
2021-01-11
2021-01-12
2021-01-13
2021-01-14
2021-01-15
2021-01-19
2021-01-20
2021-01-21
2021-01-22
2021-01-25
2021-01-26
2021-01-27
2021-01-28
2021-01-29
2021-02-01
2021-02-02
2021-02-03
2021-02-04
2021-02-05
2021-02-08
2021-02-09
2021-02-10
2021-02-11
2021-02-12
2021-02-16
2021-02-17
2021-02-18
2021-02-19
2021-02-22
2021-02-23
2021-02-24
2021-02-25
2021-02-26
2021-03-01
2021-03-02
2021-03-03
2021-03-04
2021-03-05
2021-03-08
2021-03-09
2021-03-10
2021-03-11
2021-03-12
2021-03-15
2021-03-16
2021-03-17
2021-03-18
2021-03-19
2021-03-22
2021-03-23
2021-03-24
2021-03-25
2021-03-26
2021-03-29
2021-03-30
2021-03-31
2021-04-01
2021-04-05
2021-04-06
2021-04-07
2021-04-08
2021-04-09
2021-04-12
2021-04-13
2021-04-14
2021-04-15
2021-04-16
2021-04-19
2021-04-20
2021-04-21
2021-04-22
2021-04-23
2021-04-26
2021-04-27
2021-04-28
2021-04-29
2021-04-30
2021-05-03
2021-05-04
2021-05-05
2021-05-06
2021-05-07
2021-05-10
2021-05-11
2021-05-12
2021-05-13
2021-05-14
2021-05-17
2021-05-18
2021-05-19
2021-05-20
2021-05-21
2021-05-24
2021-05-25
2021-05-26
2021-05-27
2021-05-28
2021-06-01
2021-06-02
2021-06-03
2021-06-04
2021-06-07
2021-06-08
2021-06-09
2021-06-10
2021-06-11
2021-06-14
2021-06-15
2021-06-16
2021-06-17
2021-06-18
2021-06-21
2021-06-22
2021-06-23
2021-06-24
2021-06-25
2021-06-28
2021-06-29
2021-06-30
2021-07-01
2021-07-02
2021-07-06
2021-07-07
2021-07-08
2021-07-09
2021-07-12
2021-07-13
2021-07-14
2021-07-15
2021-07-16
2021-07-19
2021-07-20
2021-07-21
2021-07-22
2021-07-23
2021-07-26
2021-07-27
2021-07-28
2021-07-29
2021-07-30
2021-08-02
2021-08-03
2021-08-04
2021-08-05
2021-08-06
2021-08-09
2021-08-10
2021-08-11
2021-08-12
2021-08-13
2021-08-16
2021-08-17
2021-08-18
2021-08-19
2021-08-20
2021-08-23
2021-08-24
2021-08-25
2021-08-26
2021-08-27
2021-08-30
2021-08-31
2021-09-01
2021-09-02
2021-09-03
2021-09-07
2021-09-08
2021-09-09
2021-09-10
2021-09-13
2021-09-14
2021-09-15
2021-09-16
2021-09-17
2021-09-20
2021-09-21
2021-09-22
2021-09-23
2021-09-24
2021-09-27
2021-09-28
2021-09-29
2021-09-30
2021-10-01
2021-10-04
2021-10-05
2021-10-06
2021-10-07
2021-10-08
2021-10-11
2021-10-12
2021-10-13
2021-10-14
2021-10-15
2021-10-18
2021-10-19
2021-10-20
2021-10-21
2021-10-22
2021-10-25
2021-10-26
2021-10-27
2021-10-28
2021-10-29
2021-11-01
2021-11-02
2021-11-03
2021-11-04
2021-11-05
2021-11-08
2021-11-09
2021-11-10
2021-11-11
2021-11-12
2021-11-15
2021-11-16
2021-11-17
2021-11-18
2021-11-19
2021-11-22
2021-11-23
2021-11-24
2021-11-26
2021-11-29
2021-11-30
2021-12-01
2021-12-02
2021-12-03
2021-12-06
2021-12-07
2021-12-08
2021-12-09
2021-12-10
2021-12-13
2021-12-14
2021-12-15
2021-12-16
2021-12-17
2021-12-20
2021-12-21
2021-12-22
2021-12-23
2021-12-27
2021-12-28
2021-12-29
2021-12-30
2021-12-31
2022-01-03
2022-01-04
2022-01-05
2022-01-06
2022-01-07
2022-01-10
2022-01-11
2022-01-12
2022-01-13
2022-01-14
2022-01-18
2022-01-19
2022-01-20
2022-01-21
2022-01-24
2022-01-25
2022-01-26
2022-01-27
2022-01-28
2022-01-31
2022-02-01
2022-02-02
2022-02-03
2022-02-04
2022-02-07
2022-02-08
2022-02-09
2022-02-10
2022-02-11
2022-02-14
2022-02-15
2022-02-16
2022-02-17
2022-02-18
2022-02-22
2022-02-23
2022-02-24
2022-02-25
2022-02-28
2022-03-01
2022-03-02
2022-03-03
2022-03-04
2022-03-07
2022-03-08
2022-03-09
2022-03-10
2022-03-11
2022-03-14
2022-03-15
2022-03-16
2022-03-17
2022-03-18
2022-03-21
2022-03-22
2022-03-23
2022-03-24
2022-03-25
2022-03-28
2022-03-29
2022-03-30
2022-03-31
2022-04-01
2022-04-04
2022-04-05
2022-04-06
2022-04-07
2022-04-08
2022-04-11
2022-04-12
2022-04-13
2022-04-14
2022-04-18
2022-04-19
2022-04-20
2022-04-21
2022-04-22
2022-04-25
2022-04-26
2022-04-27
2022-04-28
2022-04-29
2022-05-02
2022-05-03
2022-05-04
2022-05-05
2022-05-06
2022-05-09
2022-05-10
2022-05-11
2022-05-12
2022-05-13
2022-05-16
2022-05-17
2022-05-18
2022-05-19
2022-05-20
2022-05-23
2022-05-24
2022-05-25
2022-05-26
2022-05-27
2022-05-31
2022-06-01
2022-06-02
2022-06-03
2022-06-06
2022-06-07
2022-06-08
2022-06-09
2022-06-10
2022-06-13
2022-06-14
2022-06-15
2022-06-16
2022-06-17
2022-06-21
2022-06-22
2022-06-23
2022-06-24
2022-06-27
2022-06-28
2022-06-29
2022-06-30
2022-07-01
2022-07-05
2022-07-06
2022-07-07
2022-07-08
2022-07-11
2022-07-12
2022-07-13
2022-07-14
2022-07-15
2022-07-18
2022-07-19
2022-07-20
2022-07-21
2022-07-22
2022-07-25
2022-07-26
2022-07-27
2022-07-28
2022-07-29
2022-08-01
2022-08-02
2022-08-03
2022-08-04
2022-08-05
2022-08-08
2022-08-09
2022-08-10
2022-08-11
2022-08-12
2022-08-15
2022-08-16
2022-08-17
2022-08-18
2022-08-19
2022-08-22
2022-08-23
2022-08-24
2022-08-25
2022-08-26
2022-08-29
2022-08-30
2022-08-31
2022-09-01
2022-09-02
2022-09-06
2022-09-07
2022-09-08
2022-09-09
2022-09-12
2022-09-13
2022-09-14
2022-09-15
2022-09-16
2022-09-19
2022-09-20
2022-09-21
2022-09-22
2022-09-23
2022-09-26
2022-09-27
2022-09-28
2022-09-29
2022-09-30
2022-10-03
2022-10-04
2022-10-05
2022-10-06
2022-10-07
2022-10-10
2022-10-11
2022-10-12
2022-10-13
2022-10-14
2022-10-17
2022-10-18
2022-10-19
2022-10-20
2022-10-21
2022-10-24
2022-10-25
2022-10-26
2022-10-27
2022-10-28
2022-10-31
2022-11-01
2022-11-02
2022-11-03
2022-11-04
2022-11-07
2022-11-08
2022-11-09
2022-11-10
2022-11-11
2022-11-14
2022-11-15
2022-11-16
2022-11-17
2022-11-18
2022-11-21
2022-11-22
2022-11-23
2022-11-25
2022-11-28
2022-11-29
2022-11-30
2022-12-01
2022-12-02
2022-12-05
2022-12-06
2022-12-07
2022-12-08
2022-12-09
2022-12-12
2022-12-13
2022-12-14
2022-12-15
2022-12-16
2022-12-19
2022-12-20
2022-12-21
2022-12-22
2022-12-23
2022-12-27
2022-12-28
2022-12-29
2022-12-30
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-27
2023-02-28
2023-03-01
2023-03-02
2023-03-03
2023-03-06
2023-03-07
2023-03-08
2023-03-09
2023-03-10
2023-03-13
2023-03-14
2023-03-15
2023-03-16
2023-03-17
2023-03-20
2023-03-21
2023-03-22
2023-03-23
2023-03-24
2023-03-27
2023-03-28
2023-03-29
2023-03-30
2023-03-31
2023-04-03
2023-04-04
2023-04-05
2023-04-06
2023-04-10
2023-04-11
2023-04-12
2023-04-13
2023-04-14
2023-04-17
2023-04-18
2023-04-19
2023-04-20
2023-04-21
2023-04-24
2023-04-25
2023-04-26
2023-04-27
2023-04-28
2023-05-01
2023-05-02
2023-05-03
2023-05-04
2023-05-05
2023-05-08
2023-05-09
2023-05-10
2023-05-11
2023-05-12
2023-05-15
2023-05-16
2023-05-17
2023-05-18
2023-05-19
2023-05-22
2023-05-23
2023-05-24
2023-05-25
2023-05-26
2023-05-30
2023-05-31
2023-06-01
2023-06-02
2023-06-05
2023-06-06
2023-06-07
2023-06-08
2023-06-09
2023-06-12
2023-06-13
2023-06-14
2023-06-15
2023-06-16
2023-06-20
2023-06-21
2023-06-22
2023-06-23
2023-06-26
2023-06-27
2023-06-28
2023-06-29
2023-06-30
2023-07-03
2023-07-05
2023-07-06
2023-07-07
2023-07-10
2023-07-11
2023-07-12
2023-07-13
2023-07-14
2023-07-17
2023-07-18
2023-07-19
2023-07-20
2023-07-21
2023-07-24
2023-07-25
2023-07-26
2023-07-27
2023-07-28
2023-07-31
2023-08-01
2023-08-02
2023-08-03
2023-08-04
2023-08-07
2023-08-08
2023-08-09
2023-08-10
2023-08-11
2023-08-14
2023-08-15
2023-08-16
2023-08-17
2023-08-18
2023-08-21
2023-08-22
2023-08-23
2023-08-24

In [6]:
df_parquet = pd.read_parquet(DATA_PATH + f"raw/flatfiles/monthly_parquet/2016-6.parquet")
df_parquet

,datetime,open,high,low,close,volume,transactions
ticker,,,,,,,
A,2016-06-06 09:32:00,45.7200,45.78,45.72,45.780,16484,35
A,2016-06-06 09:33:00,45.8200,45.84,45.81,45.840,1128,22
A,2016-06-06 09:34:00,45.8100,45.88,45.81,45.845,2637,31
A,2016-06-06 09:35:00,45.8400,45.84,45.80,45.800,953,18
A,2016-06-06 09:36:00,45.8000,45.81,45.75,45.760,4591,46
...,...,...,...,...,...,...,...
ZYNE,2016-06-30 15:55:00,6.8900,6.90,6.89,6.900,533,7
ZYNE,2016-06-30 15:56:00,6.8900,6.89,6.85,6.860,906,13
ZYNE,2016-06-30 15:57:00,6.8600,6.86,6.85,6.850,1000,11
ZYNE,2016-06-30 15:58:00,6.8400,6.86,6.84,6.860,1930,15
ZYNE,2016-06-30 15:59:00,6.8401,6.88,6.84,6.880,1475,19

Split the monthly files which contains all ticker into individual ticker files.

In [7]:
# for year in range(2016, 2016+1):
for year in range(2016, 2026+1):
    files = []
    # for month in range(6, 6+1):
    for month in range(1, 12+1):
        print(f'{datetime.now()} | {year}-{month}')
        if not os.path.isfile(DATA_PATH + f"raw/flatfiles/monthly_parquet/{year}-{month}.parquet"):
            continue
        
        all_bars = pd.read_parquet(DATA_PATH + f"raw/flatfiles/monthly_parquet/{year}-{month}.parquet")
        all_bars = all_bars[~all_bars.index.isna()]

        if all_bars['datetime'].min().year != year or all_bars['datetime'].min().month != month:
            raise Exception(f'{year} | {month} HAS OUT OF BOUND DATES')

        # File names are case insensitive! This lead to big data errors (e.g. TpC and TPC are merged)
        # So we simply remove all tickers that have small letters.
        # Which we don't need anyways, because small letter = non-common stock.
        for ticker in list(filter(lambda ticker: not any(s.islower() for s in ticker), list(all_bars.index.unique()))):
            bars = all_bars.loc[ticker]
            if isinstance(bars, pd.Series):
                bars = all_bars.loc[[ticker]]
            bars = bars[['datetime', 'open', 'high', 'low', 'close', 'volume', 'transactions']]
            bars = bars.set_index('datetime').sort_index()
            
            # Windows quirk note: you cannot save files called 'prn'. Of course there is a ticker that is named PRN...
            # So we name it 'PRN_'. I hope there are no tickers named NULL or something please.
            # DEV: NO NEED TO DO THIS FOR MAC.
            # if ticker == 'PRN':
            #     ticker = 'PRN_'

            if os.path.isfile(DATA_PATH + f'raw/m1/{ticker}.parquet'):
                write(DATA_PATH + f"raw/m1/{ticker}.parquet", bars, append=True, compression="snappy", row_group_offsets=25000)
            else:
                bars.to_parquet(DATA_PATH + f"raw/m1/{ticker}.parquet", engine="fastparquet", compression="snappy", row_group_offsets=25000)

2026-06-07 13:02:31.623298 | 2016-1
2026-06-07 13:02:31.623526 | 2016-2
2026-06-07 13:02:31.623576 | 2016-3
2026-06-07 13:02:31.623594 | 2016-4
2026-06-07 13:02:31.623638 | 2016-5
2026-06-07 13:02:31.623765 | 2016-6
2026-06-07 13:03:04.369611 | 2016-7
2026-06-07 13:04:30.012004 | 2016-8
2026-06-07 13:06:07.309386 | 2016-9
2026-06-07 13:07:50.082866 | 2016-10
2026-06-07 13:09:39.106771 | 2016-11
2026-06-07 13:11:36.514693 | 2016-12
2026-06-07 13:13:52.099364 | 2017-1
2026-06-07 13:16:03.184448 | 2017-2
2026-06-07 13:18:10.391092 | 2017-3
2026-06-07 13:20:13.361591 | 2017-4
2026-06-07 13:22:26.882105 | 2017-5
2026-06-07 13:24:41.150172 | 2017-6
2026-06-07 13:27:01.051286 | 2017-7
2026-06-07 13:29:15.471859 | 2017-8
2026-06-07 13:31:51.387122 | 2017-9
2026-06-07 13:34:16.202088 | 2017-10
2026-06-07 13:36:41.971595 | 2017-11
2026-06-07 13:39:07.671749 | 2017-12
2026-06-07 13:41:32.860025 | 2018-1
2026-06-07 13:44:05.628518 | 2018-2
2026-06-07 13:46:33.382956 | 2018-3
2026-06-07 13:48:59.913944 | 2018-4
2026-06-07 13:51:26.679487 | 2018-5
2026-06-07 13:53:58.092339 | 2018-6
2026-06-07 13:56:29.243875 | 2018-7
2026-06-07 13:59:01.954346 | 2018-8
2026-06-07 14:01:33.682394 | 2018-9
2026-06-07 14:04:13.178926 | 2018-10
2026-06-07 14:06:56.750668 | 2018-11
2026-06-07 14:09:37.852251 | 2018-12
2026-06-07 14:12:11.640788 | 2019-1
2026-06-07 14:14:42.594505 | 2019-2
2026-06-07 14:17:15.086225 | 2019-3
2026-06-07 14:19:47.796489 | 2019-4
2026-06-07 14:22:19.074851 | 2019-5
2026-06-07 14:24:56.529982 | 2019-6
2026-06-07 14:27:24.613987 | 2019-7
2026-06-07 14:29:53.309038 | 2019-8
2026-06-07 14:32:33.042460 | 2019-9
2026-06-07 14:35:13.170231 | 2019-10
2026-06-07 14:37:56.944055 | 2019-11
2026-06-07 14:40:47.448477 | 2019-12
2026-06-07 14:43:35.669514 | 2020-1
2026-06-07 14:46:36.466628 | 2020-2
2026-06-07 14:49:27.830106 | 2020-3
2026-06-07 14:52:14.342383 | 2020-4
2026-06-07 14:55:10.712367 | 2020-5
2026-06-07 14:57:49.297385 | 2020-6
2026-06-07 15:00:41.927220 | 2020-7
2026-06-07 15:03:28.252662 | 2020-8
2026-06-07 15:06:15.094842 | 2020-9
2026-06-07 15:09:06.971692 | 2020-10
2026-06-07 15:11:57.849943 | 2020-11
2026-06-07 15:14:49.965375 | 2020-12
2026-06-07 15:17:46.874285 | 2021-1
2026-06-07 15:20:44.382348 | 2021-2
2026-06-07 15:23:38.296308 | 2021-3
2026-06-07 15:26:32.519180 | 2021-4
2026-06-07 15:29:27.270084 | 2021-5
2026-06-07 15:32:24.348457 | 2021-6
2026-06-07 15:35:13.888209 | 2021-7
2026-06-07 15:38:09.446376 | 2021-8
2026-06-07 15:41:25.786389 | 2021-9
2026-06-07 15:44:17.653000 | 2021-10
2026-06-07 15:47:16.529395 | 2021-11
2026-06-07 15:50:20.604779 | 2021-12
2026-06-07 15:53:21.694491 | 2022-1
2026-06-07 15:56:34.375108 | 2022-2
2026-06-07 15:59:57.411811 | 2022-3
2026-06-07 16:03:33.008704 | 2022-4
2026-06-07 16:06:56.437807 | 2022-5
2026-06-07 16:10:29.365088 | 2022-6
2026-06-07 16:14:00.554196 | 2022-7
2026-06-07 16:17:30.137484 | 2022-8
2026-06-07 16:21:06.627673 | 2022-9
2026-06-07 16:24:47.156723 | 2022-10
2026-06-07 16:28:23.919238 | 2022-11
2026-06-07 16:32:17.440370 | 2022-12
2026-06-07 16:35:54.295942 | 2023-1
2026-06-07 16:39:39.444004 | 2023-2
2026-06-07 16:43:02.484888 | 2023-3
2026-06-07 16:47:14.185866 | 2023-4
2026-06-07 16:50:47.849964 | 2023-5
2026-06-07 16:54:25.923955 | 2023-6
2026-06-07 16:57:58.572727 | 2023-7
2026-06-07 17:01:29.504201 | 2023-8
2026-06-07 17:04:52.467943 | 2023-9
2026-06-07 17:08:17.248107 | 2023-10
2026-06-07 17:11:44.983616 | 2023-11
2026-06-07 17:15:12.574535 | 2023-12
2026-06-07 17:18:39.038109 | 2024-1
2026-06-07 17:22:05.374333 | 2024-2
2026-06-07 17:25:29.499803 | 2024-3
2026-06-07 17:28:51.084232 | 2024-4
2026-06-07 17:32:06.809697 | 2024-5
2026-06-07 17:35:29.827924 | 2024-6
2026-06-07 17:38:47.726638 | 2024-7
2026-06-07 17:42:13.397911 | 2024-8
2026-06-07 17:45:32.889589 | 2024-9
2026-06-07 17:48:57.135614 | 2024-10
2026-06-07 17:52:15.762565 | 2024-11
2026-06-07 17:55:24.375758 | 2024-12
2026-06-07 17:58:39.626667 | 2025-1
2026-06-07 18:01:55.578035 | 2025-2
2026-06-07 18:05:09.490829 | 2025-3
2026-06-07 18:08:29.321470 | 2025-4
2026-06-07 18:11:51.183439 | 2025-5
2026-06-07 18:15:37.999326 | 2025-6
2026-06-07 18:19:11.041566 | 2025-7
2026-06-07 18:22:31.653441 | 2025-8
2026-06-07 18:26:07.803608 | 2025-9
2026-06-07 18:29:39.460693 | 2025-10
2026-06-07 18:33:04.098324 | 2025-11
2026-06-07 18:36:29.901340 | 2025-12
2026-06-07 18:39:55.231360 | 2026-1
2026-06-07 18:43:17.024503 | 2026-2
2026-06-07 18:46:52.620618 | 2026-3
2026-06-07 18:50:37.962823 | 2026-4
2026-06-07 18:54:16.722853 | 2026-5
2026-06-07 18:57:45.787259 | 2026-6
2026-06-07 19:01:00.586241 | 2026-7
2026-06-07 19:01:00.586626 | 2026-8
2026-06-07 19:01:00.586968 | 2026-9
2026-06-07 19:01:00.586983 | 2026-10
2026-06-07 19:01:00.586993 | 2026-11
2026-06-07 19:01:00.587003 | 2026-12

In [13]:
ticker_parquet = pd.read_parquet(DATA_PATH + f"raw/m1/AA.parquet")
ticker_parquet

                     open  high   low  close  volume  transactions
datetime
2016-06-06 04:53:00  9.55  9.55  9.55   9.55    1000             2
2016-06-06 05:20:00  9.56  9.56  9.55   9.56    1200             5
2016-06-06 05:47:00  9.60  9.61  9.60   9.61    1380            13
2016-06-06 06:10:00  9.57  9.57  9.57   9.57     400             1
2016-06-06 06:54:00  9.60  9.60  9.60   9.60     100             1
...                   ...   ...   ...    ...     ...           ...
2016-06-30 18:09:00  9.27  9.27  9.27   9.27    1550             1
2016-06-30 18:14:00  9.25  9.25  9.25   9.25    9040             4
2016-06-30 18:17:00  9.24  9.24  9.24   9.24     790             1
2016-06-30 18:54:00  9.27  9.27  9.27   9.27    1300             1
2016-06-30 19:09:00  9.24  9.24  9.24   9.24     100             1

[8337 rows x 6 columns]

The old version of the above code runs very fast, up to end 2022. Then it becomes 20-50x slower. I found the problem:

Pandas dataframe lookup uses hash-tables so the time complexity is O(1). However, if you have null values in the index this does not apply anymore! The bars from end 2022 and upwards have null values.

# Updates
Process day-by-day

In [ ]:
def process_flatfile(local_file_path):
    """Unzips the flat file and split or append it to ticker files.
    """
    with gzip.open(local_file_path) as f:
        all_bars = pd.read_csv(f)
        all_bars = all_bars[['window_start', 'ticker', 'open', 'high', 'low', 'close', 'volume', 'transactions']]
        all_bars = all_bars.rename(columns={'window_start': 'datetime'})
        all_bars = all_bars.set_index('datetime')
        all_bars.index = pd.to_datetime(all_bars.index, unit='ns') # Convert to datetime (UTC-naive)
        all_bars.index = all_bars.index.tz_localize(pytz.UTC)  # Make UTC aware (in order to convert)
        all_bars.index = all_bars.index.tz_convert("US/Eastern")  # Convert UTC to ET
        all_bars.index = all_bars.index.tz_localize(None)  # Make timezone naive
        
        for ticker in all_bars['ticker'].unique():
            bars = all_bars[all_bars['ticker'] == ticker]
            bars = bars[['open', 'high', 'low', 'close', 'volume', 'transactions']]

            if os.path.isfile(DATA_PATH + f'raw/m1/{ticker}.parquet'):
                write(DATA_PATH + f"raw/m1/{ticker}.parquet", bars, append=True, compression="snappy", row_group_offsets=25000)
            else:
                bars.to_parquet(DATA_PATH + f"raw/m1/{ticker}.parquet", engine="fastparquet", compression="snappy", row_group_offsets=25000)

In [ ]:
for day in get_market_dates(START_DATE, END_DATE):
    destination = DATA_PATH + f'raw/{day.isoformat()}.csv.gz' # DEV: THIS SEEMS WORNG! NO M1 OR FLATFILES FOLDER ??
    s3.download_file('flatfiles', 
                 f'us_stocks_sip/minute_aggs_v1/{day.year}/{day.strftime("%m")}/{day.isoformat()}.csv.gz', 
                 destination)
    process_flatfile(destination)